config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  authenticated :admin do
   root 'admin#index', as: :root
   end

 unauthenticated :admin do
   root 'home#index', as: :unauthenticated_root
 end

  get 'admin' => 'admin#index'

  get 'contact' => 'home#contact'

  get 'menu' => 'home#menu'

  resources :messages

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :name, :email, :phone, :message, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
    @messages = Message.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def menu
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
	@message = Message.new(messages_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to root_url, notice: 'News was successfully created.' }
      else
        format.html { redirect_to :back }
      end
    end
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		respond_to do |format|
         format.html { redirect_to admin_url, notice: 'News was successfully destroyed.' }
        end
	end

	private

	def messages_params
		params.require(:message).permit(:name, :email, :phone, :message)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h2 class="text-center" style="padding: 60px 0;color:#fff;">All Messages</h2>
<div style="position:absolute;top: 30px;right: 70px;">
<%= link_to 'Logout', destroy_admin_session_path ,method: :delete, :class => 'fy-logout-button fy-button-accent' %>
</div>
<div style="display:flex;justify-content:center;width:100%;min-height:100vh;padding: 50px 30px;">


  <div class="numberlist" style="overflow-x: auto;">
              <table>
                <thead>
                      <tr>
                      <th>Sl no.</th>
                      <th>Name of Sender</th>
                      <th>Contact No.</th>
                      <th>Email of Sender</th>
                      <th>Message of Sender</th>
                     <% if current_admin %> <th>Remove</th> <% end %>
                    </tr>
                </thead>
                  <tbody>
                      <% i = 0 %>
                      <% @messages.each do |message| %>
                      <% i = i.to_i + 1%>
                      <tr>
                          <td><%= i %></td>
                          <td><%= message.name %></td>
                          <td><%= message.phone %></td>
                          <td><%= message.email %></td>
                          <td><%= message.message %></td>
                        <% if current_admin %>  <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td> <% end %>
                      </tr>
                      <% end %>
                  </tbody>
              </table>
          </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <title>Rolling Ball</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

  <meta content="Rolling Ball" name="description" />
  <meta content="Quadtrust " name="author" />

  <%= stylesheet_link_tag 'application' %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'application' %>
</body>
</html>